In [1]:
from google.colab import drive
drive.mount(r'/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import re

In [3]:
df=pd.read_csv("/content/drive/My Drive/Colab Notebooks/Feynn Labs/ev/data/three_wheelers.csv")
df.head()

,name,price,power,gvw,milage,engine,fual_tank,payload,fuel_type
0,Bajaj Maxima Cargo E-TEC 9.0,Price Coming Soon,6 Hp,NaN,NaN,NaN,NaN,NaN,Electric
1,Bajaj Maxima Xl Cargo E-TEC 12.0,From ₹3.77 Lakh*,7 hp,NaN,NaN,NaN,NaN,NaN,Electric
2,Piaggio Ape Xtra LDX,₹2.45 - ₹2.48 Lakh*,9.4 hp,975,22,599,10.5,-,NaN
3,Bajaj Maxima C,₹2.83 - ₹2.84 Lakh*,10 hp,965,33,470.5,8,NaN,Diesel
4,Mahindra Alfa Plus,₹2.59 - ₹2.85 Lakh*,9 hp,995,29.4,597,NaN,505,Diesel

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       234 non-null    object
 1   price      234 non-null    object
 2   power      209 non-null    object
 3   gvw        188 non-null    object
 4   milage     140 non-null    object
 5   engine     131 non-null    object
 6   fual_tank  123 non-null    object
 7   payload    183 non-null    object
 8   fuel_type  115 non-null    object
dtypes: object(9)
memory usage: 16.6+ KB

In [6]:
def extract_price(text):
    if text=='Price Coming Soon':
        return 0.001
    elif text.find(',')!=-1:
      partten="(\d+.\d+|d+,\d+)"
#     print(text)
      match=re.search(partten,text)
      tmp=match.group(1).split(',')
      # print(tmp)
      return float(''.join(tmp))/100000

    partten="(\d+.\d+|d+)"
#     print(text)
    match=re.search(partten,text)
    return float(match.group(1))
df['price_new']=df['price'].apply(extract_price)
df['price_new']

0      0.001
1      3.770
2      2.450
3      2.830
4      2.590
       ...
229    0.001
230    0.001
231    0.001
232    0.001
233    0.001
Name: price_new, Length: 234, dtype: float64

In [7]:
def extract_brand(text):
  try:
    return text.split()[0]
  except:
    return text
df['brand']=df['name'].apply(extract_brand)
df['brand'].unique()

array(['Bajaj', 'Piaggio', 'Mahindra', 'Atul', 'Euler', 'Mini', 'TVS',
       'Altigreen', 'YC', 'Dandera', 'SN', 'Kinetic', 'E-Ashwa', 'OSM',
       'JSA', 'City', 'ADM', 'Baxy', 'Tejas', 'Lohia', 'Gkon', 'Saarthi',
       'Udaan', 'Thukral', 'Etron', 'Deltic', 'Keto', 'Avon', 'Terra',
       'GreenRick', 'Jitendra', 'Saera', 'Erisha', 'Star', 'Ele',
       'E-Trio', 'Grevol', '3evi', 'ADAPT', 'Zero21', 'Skyride', 'Vande',
       'Speego', 'Allfine', 'Panther', 'Greaves', 'Badshah', 'Bahubali',
       'E-Maggic', 'Gopal', 'Gk', 'Top', 'Hooghly', 'Bhave', 'BYBY',
       'Singham', 'Arzoo', 'G.R.D', 'Diamond', 'Reep', 'Om', 'E-Ranger',
       'Khalsa', 'Jangid', 'Nova', 'NRJ', 'Biliti', 'Indo', 'Rajhans',
       'Atut', 'Divya', 'Move', 'BABA', 'Vani', 'Kuku', 'GEM', 'Janaasha',
       'Victory', 'OK', 'Gayam', 'ETO'], dtype=object)

In [8]:
def extract_power(text):
    text=str(text)
    if text==None:
        return None
    wat = 'Watt' or 'W'
    partten="(\d+.\d+|\d+)"

    if re.search('Watt|W',text):
      # partten="(\d+)"
      match=re.search(partten,text)
      # print(round(float(match.group(1))/746,2))
      return round(float(match.group(1))/746,2)
      # print(text)
    else:
      # print(text)
      match=re.search(partten,str(text))
      try:
          return round(float(match.group(1)),2)
      except:
          return None
df['power_new']=df['power'].apply(extract_power)
# df['power_new'].unique()

In [9]:
def extract_int(text):
    text=str(text)
    try:
        return float(text)
    except:
        partten="(\d+)"
#     print(text)
        match=re.search(partten,text)
        try:
            return float(match.group(1))
        except:
            return None
df['payload'].apply(extract_int).isna().sum()

107

In [10]:
def extract_int(text):
    text=str(text)
    try:
        return float(text)
    except:
        partten="(\d+)"
#     print(text)
        match=re.search(partten,text)
        try:
            return float(match.group(1))
        except:
            return None
df['gvw_new']=df['gvw'].apply(extract_int)
df['milage_new']=df['milage'].apply(extract_int)
df['engine_new']=df['engine'].apply(extract_int)
df['fuel_tank_new']=df['fual_tank'].apply(extract_int)
df['payload_new']=df['payload'].apply(extract_int)
# df['payload_new']

In [13]:
df_=df[df['price_new']!=0.001]
cols=['name', 'brand','price_new', 'power_new', 'gvw_new',
       'milage_new', 'engine_new', 'fuel_tank_new', 'payload_new', 'fuel_type']
df_new=df_[cols]
df_new.columns=['name', 'brand','price', 'power', 'gvw','milage', 'engine','fuel_tank', 'payload', 'fuel_type']
df_new.head()

In [ ]:
df_new.to_csv("/content/drive/My Drive/Colab Notebooks/Feynn Labs/ev/clean_data/three_wheelers_clean.csv",
               index=False, encoding='utf-8-sig')